export const SERVICES=[
    {
        libelle:'Dépot et retrait tremo',
        proprietaire:'RB SERVICE',
        description:'Dépot et retrait tremo sur les comptes wave, orange et MTN',
        disponibilite:'Disponible 24H/24',
        image:'https://picsum.photos/200/300?random=3',
    },
    {
        libelle:'Dépot et retrait tremo',
        proprietaire:'RB SERVICE',
        description:'Dépot et retrait tremo sur les comptes wave, orange et MTN',
        disponibilite:'Disponible 24H/24',
        image:'https://picsum.photos/200/300?random=3',
    },
    {
        libelle:'Dépot et retrait tremo',
        proprietaire:'RB SERVICE',
        description:'Dépot et retrait tremo sur les comptes wave, orange et MTN',
        disponibilite:'Disponible de 07h à 22h',
        image:'https://picsum.photos/200/300?random=3',
    },
    {
        libelle:'Dépot et retrait tremo',
        proprietaire:'RB SERVICE',
        description:'Dépot et retrait tremo sur les comptes wave, orange et MTN',
        disponibilite:'Disponible 24H/24',
        image:'https://picsum.photos/200/300?random=3',
    },
    {
        libelle:'Dépot et retrait tremo',
        proprietaire:'RB SERVICE',
        description:'Dépot et retrait tremo sur les comptes wave, orange et MTN',
        disponibilite:'Disponible 24H/24',
        image:'https://picsum.photos/200/300?random=3',
    },
    {
        libelle:'Dépot et retrait tremo',
        proprietaire:'RB SERVICE',
        description:'Dépot et retrait tremo sur les comptes wave, orange et MTN',
        disponibilite:'Disponible 24H/24',
        image:'https://picsum.photos/200/300?random=3',
    },
    {
        libelle:'Dépot et retrait tremo',
        proprietaire:'RB SERVICE',
        description:'Dépot et retrait tremo sur les comptes wave, orange et MTN',
        disponibilite:'Disponible 24H/24',
        image:'https://picsum.photos/200/300?random=3',
    },
    {
        libelle:'Dépot et retrait tremo',
        proprietaire:'RB SERVICE',
        description:'Dépot et retrait tremo sur les comptes wave, orange et MTN',
        disponibilite:'Disponible 24H/24',
        image:'https://picsum.photos/200/300?random=3',
    },
    {
        libelle:'Dépot et retrait tremo',
        proprietaire:'RB SERVICE',
        description:'Dépot et retrait tremo sur les comptes wave, orange et MTN',
        disponibilite:'Disponible 24H/24',
        image:'https://picsum.photos/200/300?random=3',
    },
    {
        libelle:'Dépot et retrait tremo',
        proprietaire:'RB SERVICE',
        description:'Dépot et retrait tremo sur les comptes wave, orange et MTN',
        disponibilite:'Disponible 24H/24',
        image:'https://picsum.photos/200/300?random=3',
    },
    {
        libelle:'Dépot et retrait tremo',
        proprietaire:'RB SERVICE',
        description:'Dépot et retrait tremo sur les comptes wave, orange et MTN',
        disponibilite:'Disponible 24H/24',
        image:'https://picsum.photos/200/300?random=3',
    },
];